/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as CreateOpenCollectionScriptJson } from "../scripts/CreateOpenCollection.ral.json";
import { default as MintOpenNFTScriptJson } from "../scripts/MintOpenNFT.ral.json";

export const CreateOpenCollection = new ExecutableScript<{
  openCollectionTemplateId: HexString;
  nftTemplateId: HexString;
  collectionUri: HexString;
  collectionOwner: Address;
  totalSupply: bigint;
}>(
  Script.fromJson(CreateOpenCollectionScriptJson, "", []),
  getContractByCodeHash
);

export const MintOpenNFT = new ExecutableScript<{
  nftCollectionId: HexString;
  uri: HexString;
}>(Script.fromJson(MintOpenNFTScriptJson, "", []), getContractByCodeHash);
